abstract class AppStrings {
  static const String appName = 'Car Wash App',
      getStarted = 'Get Started',
      welcomeTo = 'Welcome to Car Wash!',
      experienceThe = 'Experience the ',
      ultimateCarWash = '\nUltimate Car Wash',
      signIn = 'Sign in',
      signUp = 'Sign up',
      login = 'Login',
      fullName = 'Full Name',
      email = 'E-mail',
      password = 'Password',
      repeatPassword = 'Repeat Password',
      forgetPassword = 'Forget Password ?',
      orLoginWith = 'or login with',
      signIntoYourAccount = 'Sign in to your \naccount',
      welcomeBack = 'Welcome Back!',
      dontHaveAccount = 'Don\'t have an account?  ',
      alreadyHaveAccount = 'Already have an account?',
      createAccount = 'Create Account',
      joinUsWeWashCarsYouRetax = 'Join us now!!! We Wash Cars. You Retax',
      selectMethodToLogIn = 'Select method to log in:',
      beforewestart = 'Before we start!',
      selectYourCarType =
          'Select your car type so we can adjust our prices for you!',
      save = 'Save',
      hintTextEmail = 'someone@example.com',
      hintTextPassword = '****************',
      rememberMe = 'Remember me';
}
