name: car_wash_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

 
dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0  
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0 
  firebase_storage: ^12.2.0
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  #? using dartz for error handling 
  dartz: ^0.10.1
  #? Networking
  dio: ^5.7.0
  #? State management
  flutter_bloc: ^8.1.6
  #? An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.10+1
  #? Flutter Toast
  fluttertoast: ^8.2.8
  #? for dependency injection
  get_it: ^7.7.0
  #? storage for simple data in local storage
  shared_preferences: ^2.3.2
  #? for splash screen native 
  flutter_native_splash: ^2.4.1
 
  gap: ^3.0.1
  intl: ^0.19.0
  skeletonizer: ^1.4.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  #? A package which simplifies the task of updating your Flutter app's launcher icon
  flutter_launcher_icons: "^0.13.1"


# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/icons/logo.png"

 
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/icons/
  - assets/images/
  
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
 
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
