// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7g_wfbljeUFmANlUWTFyfV4bwLj5A-U0',
    appId: '1:640272351869:web:8d6cd733cff00a08ff6714',
    messagingSenderId: '640272351869',
    projectId: 'car-wash-dc7ff',
    authDomain: 'car-wash-dc7ff.firebaseapp.com',
    storageBucket: 'car-wash-dc7ff.appspot.com',
    measurementId: 'G-K0D909QJRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARrgloEa2XMZXQt8rAJ_p427d907kWjGs',
    appId: '1:640272351869:android:e5a15a0f580d308aff6714',
    messagingSenderId: '640272351869',
    projectId: 'car-wash-dc7ff',
    storageBucket: 'car-wash-dc7ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtryMEIMGVVXs75A8-kgOFKLzRTmcPOWQ',
    appId: '1:640272351869:ios:89a5c723c8bab4d4ff6714',
    messagingSenderId: '640272351869',
    projectId: 'car-wash-dc7ff',
    storageBucket: 'car-wash-dc7ff.appspot.com',
    iosBundleId: 'com.example.carWashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtryMEIMGVVXs75A8-kgOFKLzRTmcPOWQ',
    appId: '1:640272351869:ios:89a5c723c8bab4d4ff6714',
    messagingSenderId: '640272351869',
    projectId: 'car-wash-dc7ff',
    storageBucket: 'car-wash-dc7ff.appspot.com',
    iosBundleId: 'com.example.carWashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7g_wfbljeUFmANlUWTFyfV4bwLj5A-U0',
    appId: '1:640272351869:web:a0a46e0b6f2c0a30ff6714',
    messagingSenderId: '640272351869',
    projectId: 'car-wash-dc7ff',
    authDomain: 'car-wash-dc7ff.firebaseapp.com',
    storageBucket: 'car-wash-dc7ff.appspot.com',
    measurementId: 'G-S8YVMMT21R',
  );
}
